# Generated by Django 3.2.9 on 2022-01-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='Image_url',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
