# Generated by Django 3.2.9 on 2022-01-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_listing_auction_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='Auction_open',
            field=models.BooleanField(default=True),
        ),
    ]
