# Generated by Django 3.2.9 on 2022-01-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_listing_auction_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='Start_bid',
            new_name='current_price',
        ),
    ]
