# Generated by Django 3.2.9 on 2022-01-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_start_bid_auction_listing_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Items',
            field=models.ManyToManyField(null=True, to='auctions.Auction_listing'),
        ),
    ]
