# Generated by Django 3.2.9 on 2022-01-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_category_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Items',
            field=models.ManyToManyField(blank=True, to='auctions.Auction_listing'),
        ),
    ]
