# Generated by Django 3.2.9 on 2022-01-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_category_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='Image_url',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
